### ISSUE TITLE
Disable tracing of discovery client calls

### ISSUE THREAD

**Issue by ZacharyKlein** [micronaut-projects/micronaut-tracing#11]
When using distributed tracing with service discovery enabled, all health checks/service updates are traced.

Sample project:

https://github.com/ZacharyKlein/micronaut-microservices-distributed-tracing-jaeger/tree/master/complete

**Comment by timyates** [comment]
I submitted a PR (mistakenly) to micronaut-core over here

https://github.com/micronaut-projects/micronaut-core/pull/6768

Working on migrating that to this project instead. @burtbeckwith are changes required in core to mirror any made here?

**Comment by yawkat** [comment]
no, I didnt have to copy the changes in #4

**Comment by timyates** [comment]
👍
