### ISSUE TITLE
OpenTelemetry HTTP should report low cardinality route names with {id} masked in metrics

### ISSUE THREAD

**Issue by pixnbit** [micronaut-projects/micronaut-tracing#181]
I wanted to group my traces but APIs with `id`s on the path are reported with the `id` value, not the template ones. Quote from OpenTelemtry:

> HTTP spans MUST follow the overall [guidelines for span names](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#span). Many REST APIs encode parameters into URI path, e.g. /api/users/123 where 123 is a user id, which creates high cardinality value space not suitable for span names. In case of HTTP servers, these endpoints are often mapped by the server frameworks to more concise HTTP routes, e.g. /api/users/{user_id}, which are recommended as the low cardinality span names. However, the same approach usually does not work for HTTP client spans, especially when instrumentation is provided by a lower-level middleware that is not aware of the specifics of how the URIs are formed. Therefore, HTTP client spans SHOULD be using conservative, low cardinality names formed from the available parameters of an HTTP request, such as "HTTP {METHOD_NAME}". Instrumentation MUST NOT default to using URI path as span name, but MAY provide hooks to allow custom logic to override the default span name.

>  http.route | string | The matched route (path template in the format used by the respective server framework). See note below [1] | /users/:userID?; {controller}/{action}/{id?}

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md:

In `MicronautHttpServerAttributesGetter`, instead of `request.getAttribute(HttpAttributes.ROUTE_INFO);`, should we use `request.getAttribute(HttpAttributes.URI_TEMPLATE)`, which is `.route.template`?

My slow query dashboard is now this, I wanted them to be grouped without the actuals `id`s:

<img width="638" alt="image" src="https://user-images.githubusercontent.com/729730/193432017-e1124bc2-b158-45ab-996f-b0ec7755a72d.png">

I guess I could have my own replacement implementation but I also want to check if this should be a valid case supported officially

### Version

4.4.0

**Comment by graemerocher** [comment]
Yes I agree `URI_TEMPLATE` should be used. Would you like to send a PR?
