### ISSUE TITLE
Bug/OpenTelemetry HTTP Server - span attribute 'http.route' is not respecting the defined template

### ISSUE THREAD

**Issue by arik-dig** [micronaut-projects/micronaut-tracing#220]
### Expected Behavior

span attribute `http.route` value is `/users/get/{username}` .

the [OpenTelemetry HTTP Server semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#http-server-semantic-conventions) suggests that `http.route` would be the 

> path template in the format used by the respective server framework

### Actual Behaviour

span attribute `http.route` value is `/users/johnd` .

### Steps To Reproduce

define JAX-RS resource:

```
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;

@Path("users")
public class UsersResource {

    @GET
    @Path("get/{username}")
    public String getByUsername(@PathParam("username") String username) {
        return "User is " + username;
    }
}
```

### Version

micronaut core version - 3.7.5 
micronaut tracing version - 4.4.0 
micronaut gradle plugin io.micronaut.application version 3.6.7

**Comment by arik-dig** [comment]
attaching jaeger trace

![image](https://user-images.githubusercontent.com/104715391/210591785-7abe23de-e9cc-4047-9ead-b0a85f99c79c.png)

**Comment by arik-dig** [comment]
seems like that in PR #149, it reads attribute ROUTE_INFO **before** URI_TEMPLATE.
I guess it should be the opposite

**Comment by n0tl3ss** [comment]
Hi @arik-dig try to update micronaut-tracing to `4.5.0` version

**Comment by arik-dig** [comment]
@n0tl3ss it seems to work with 4.5.0.
BTW, I work with gradle plugin io.micronaut.application version 3.7.0 - and it seems that it takes micronaut-tracing 4.4.0.
in which version of the gradle plugin it will point to tracing 4.5.x?

**Comment by sdelamo** [comment]
Micronaut Framework 3.9.0 BOM (Bill-Of-Materials) will include Micronaut Tracing 4.5.0. You can start using by forcing the version by setting in `build.gradle`: 

```
configurations.all {
    resolutionStrategy {
        force "io.micronaut.tracing:micronaut-tracing-opentelemetry-http:4.5.0"
    }
}
```
