### ISSUE TITLE
Reactor contextView doesn't contain ServerRequestContext when zipkin enabled

### ISSUE THREAD

**Issue by ondrej-hrstka** [micronaut-projects/micronaut-tracing#29]
### Expected Behavior

Reactor `Context` should contain `HttpRequest` when accessed in endpoint method.

### Actual Behaviour

Reactor `Context` is empty when accessed in endpoint method.

### Steps To Reproduce

1. Run the example App
2. run `curl http://localhost:8080/test`

### Environment Information

- OS: Mac OS X Monterey
- JDK 17

### Example Application

https://github.com/ondrej-hrstka/micronaut_broken_reactor_context

### Version

3.3.1

**Comment by graemerocher** [comment]
Related to https://github.com/micronaut-projects/micronaut-tracing/commit/961c38c4cc9eeba420e8f9a767156dc03503780d

**Comment by graemerocher** [comment]
@n0tl3ss can you check if this is still a problem?
