### ISSUE TITLE
Wrapped Kafka consumer does not respond to WakeupExceptions

### ISSUE THREAD

**Issue by ptiredknees** [micronaut-projects/micronaut-tracing#379]
### Expected Behavior

Kafka consumers should exit the poll loop when a `WakeupException` is raised.

### Actual Behaviour

The OpenTelemetry consumer proxy wraps any exception in a `InvocationTargetException` and this ends up being passed to through to the exception handler. The poll loop does not exit which prevents tests from completing.

### Version

4.03

**Comment by guillermocalvo** [comment]
Closed by https://github.com/micronaut-projects/micronaut-tracing/pull/384.
