### ISSUE TITLE
Update to 1.32.0+ breaks Kafka integration

### ISSUE THREAD

**Issue by timyates** [micronaut-projects/micronaut-tracing#479]
### Feature description

Currently we are on 1.31.x and 1.32.x

1.32.0 is the latest version at time of writing that all opentracing libraries have (they seem to release at a different rate to each other)

When we update to 1.32.x, the kafka module breaks as we use internal classes where methods we use have been removed.

I took a look, but it's not an insignificant change and I believe it would be a binary breaking change for us.

**Comment by sdelamo** [comment]
@jeremyg484 @timyates what is the status of this? We updated to 1.36.0

**Comment by jeremyg484** [comment]
> @jeremyg484 @timyates what is the status of this? We updated to 1.36.0

@sdelamo 
The [update to 1.36.0](https://github.com/micronaut-projects/micronaut-tracing/commit/98d256b2fd3e42ff3718728362b48a31d8d0d1f2) did require some minor changes to the Kafka instrumentation, but nothing that was a breaking change to our API, so I think we can close this.
