### ISSUE TITLE
MN OTel HTTP add API dependencies on the annotation processor libraries

### ISSUE THREAD

**Issue by musketyr** [micronaut-projects/micronaut-tracing#553]
### Expected Behavior

Annotation processor libraries such as Micronaut Core Processor should not be added to the runtime classpath.

### Actual Behaviour

Micronaut OpenTelemetry HTTP depends on Micronaut OpenTelemetry Annotations that depends on Micronaut Core Processor that for example pulls unnecessary 7.1 MB JAR of Java Parser.

### Steps To Reproduce

You can follow the [OpenTelementry guide](https://guides.micronaut.io/latest/micronaut-microservices-distributed-tracing-jaeger-opentelemetry-gradle-java.html). Once the following dependency is added you can see that there are also Micronaut Core Processor and Java Parser on the classpath.

```
implementation("io.micronaut.tracing:micronaut-tracing-opentelemetry-http")
```

![Snímek obrazovky 2024-04-29 v 13 11 03](https://github.com/micronaut-projects/micronaut-tracing/assets/660405/4cd4fe0f-dca6-406b-842b-73b6090cd9f6)

### Example Application

https://guides.micronaut.io/latest/micronaut-microservices-distributed-tracing-jaeger-opentelemetry-maven-java.html#micronaut-opentelemetry-http

### Version

4.3.8

**Comment by timyates** [comment]
I will work on splitting the annotation classes away from the processors ([as we did for EclipseStore](https://github.com/micronaut-projects/micronaut-eclipsestore/pull/15)).

This will be a major change, so will need to be in Micronaut 5

**Comment by timyates** [comment]
Actually, I may have spoken too soon...  Investigating...
