### ISSUE TITLE
Move from Open Tracing to Open Telemetry 

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-tracing#7]
Tracing module is now an independent project and we need to undertake the refactoring work to move to Open Telemetry. Tasks:

- [ ] Split tracing annotations to new `tracing-annotation` module
- [ ] Remove the references to TracingInterceptor from the annotations and use the `@InterceptorBinding` approach instead https://github.com/micronaut-projects/micronaut-tracing/blob/afe860b1522cec6bcf7cffcbdd43e83eba0aedca/tracing-core/src/main/java/io/micronaut/tracing/annotation/ContinueSpan.java#L42
- [ ] Create a new `tracing-opentelemetry` module that doesn't depend on Open Tracing but uses the same annotations with an interceptor binding. A new interceptor will be needed
- [ ] Add instrumentations for Open Telemetry
- [ ] Possibly add a module for AWS https://aws-otel.github.io/docs/getting-started/java-sdk
- [ ] Documentation

**Comment by gijsleussink** [comment]
How can we help moving this forward? 💪

**Comment by donbeave** [comment]
I think it will be nice to add support for official OpenTelemetry java annotations: https://opentelemetry.io/docs/instrumentation/java/automatic/annotations/

I can come up with a PR, which will add support for `@WithSpan` and `@SpanAttribute` annotations.

Also, I think it's better to use official opentelemetry java instrumentation libraries for instrumentation: https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation

I can help with this work as well.

**Comment by trask** [comment]
> Also, I think it's better to use official opentelemetry java instrumentation libraries for instrumentation: https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation

here's a list of instrumentation which can be used (so far) without the javaagent:
https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/standalone-library-instrumentation.md

**Comment by graemerocher** [comment]
@donbeave there is a WIP PR at https://github.com/micronaut-projects/micronaut-tracing/pull/65 perhaps you can provide @n0tl3ss with feedback

**Comment by ZawadaZSE** [comment]
Hey 👋

Do you have some estimates when will this be released?

**Comment by graemerocher** [comment]
In a Micronaut release in 3.6.0 time frame (aprox 5 weeks from now), we will probably release the module sooner though, in the meantime you can try the snapshots https://github.com/micronaut-projects/micronaut-tracing/pull/65#issuecomment-1138686717

**Comment by driverpt** [comment]
1 Question folks, does this integrate with Logback's MDC ?

**Comment by donbeave** [comment]
> 1 Question folks, does this integrate with Logback's MDC ?

Not automatically by Micronaut Tracing module yet, you can do it by adding the OTEL appender by following this instruction: https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/logback/logback-mdc-1.0/library
